stages:
  - building
  - test

gcc:
  stage: building
  before_script:
    - mkdir build
    - cd build
    - conan install ../ -s build_type=Debug --profile gcc
  script:
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_BUILD_TYPE=Release
      -DTEST=true
      ..
    - cmake --build .
  artifacts:
    paths:
      - build/bin/mat_integral_test
      - build/bin/mat_matches_test

google-gcc:
  stage: test
  dependencies:
    - gcc
  script:
    - ./build/bin/mat_integral_test
    - ./build/bin/mat_matches_test
